#!/bin/bash
cd /home/api/Desktop/abook/abook/
echo "execution at:"
pwd
echo "Python environment set"

source venv/bin/activate

echo "launch app"

python src/main.py >> "logs/$(date +"%Y_%m_%d_%I_%M_%p").log"