
import types

# button constants
BUTTONS = types.SimpleNamespace()
BUTTONS.BUTTON_A='BUTTON_A'
BUTTONS.BUTTON_B='BUTTON_B'
BUTTONS.BUTTON_C='BUTTON_C'
BUTTONS.BUTTON_D='BUTTON_D'
BUTTONS.BUTTON_E='BUTTON_E'

# SYSTEM PROPERTIES
SYSTEM_PROPERTIES = types.SimpleNamespace()
#TODO - fix
SYSTEM_PROPERTIES.LAST_CAST_DEVICE = 'Attic Hub'