
import types

# button constants
BUTTONS = types.SimpleNamespace()
BUTTONS.BUTTON_A='BUTTON_A'
BUTTONS.BUTTON_B='BUTTON_B'
BUTTONS.BUTTON_C='BUTTON_C'
BUTTONS.BUTTON_D='BUTTON_D'
BUTTONS.BUTTON_E='BUTTON_E'

# dialog constants
DIALOGS = types.SimpleNamespace()
DIALOGS.WELCOME='WELCOME'
DIALOGS.CHOOSE_CAST='CHOOSE_CAST'
DIALOGS.CHOOSE_WIFI='CHOOSE_WIFI'
DIALOGS.CHOOSE_AUDIOBOOK='CHOOSE_AUDIOBOOK'
DIALOGS.AUDIOBOOK_PLAY='AUDIOBOOK_PLAY'
DIALOGS.TEST='TEST'

# actions
ACTIONS = types.SimpleNamespace()
ACTIONS.NAVIGATE='NAVIGATE'
ACTIONS.VOL_UP='VOL_UP'
ACTIONS.VOL_DOWN='VOL_DOWN'

# SYSTEM PROPERTIES
SYSTEM_PROPERTIES = types.SimpleNamespace()
SYSTEM_PROPERTIES.LAST_CAST_DEVICE = 'last-cast-device'